services:
  
  web-app:
    build:
        context: .
        dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - mysql

volumes:
  mysql-data: